{% set name = "czekitout" %}
{% set version = "0.0.1" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/czekitout-{{ version }}.tar.gz
  sha256: da5a75a723b52ed1e89d614c7cd1b4482afff9f2fb96c825d018bdd9f4303942

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 0

requirements:
  host:
    - python >=3.8
    - setuptools
    - wheel
    - setuptools-scm
    - pip
  run:
    - python >=3.8
    - numpy

test:
  imports:
    - czekitout
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/czekitout/
  summary: Contains a collection of functions that facilitate validation, and type-conversions, with useful error messages when exceptions are thrown.
  dev_url: https://github.com/mrfitzpa/czekitout
  license: GPL-3.0
  license_file: LICENSE

extra:
  recipe-maintainers:
    - mrfitzpa
