{% set name = "czekitout" %}
{% set version = "1.0.0" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/czekitout-{{ version }}.tar.gz
  sha256: 6646539124ddf93a26ebb420f00ee761712c24b41aafe2f15123ac2d1981b934

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
  number: 1

requirements:
  host:
    - python >=3.8
    - setuptools
    - wheel
    - setuptools-scm
    - pip
  run:
    - python >=3.8
    - numpy

test:
  imports:
    - czekitout
  commands:
    - pip check
  requires:
    - pip

about:
  home: https://pypi.org/project/czekitout/
  summary: Contains a collection of functions that facilitate validation, and type-conversions, with useful error messages when exceptions are thrown.
  dev_url: https://github.com/mrfitzpa/czekitout
  license: GPL-3.0-only
  license_file: LICENSE

extra:
  recipe-maintainers:
    - mrfitzpa
